services:
  database:
    image: docker.io/library/postgres:16-alpine
    container_name: trusty_chain_container
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=trustychain
      - POSTGRES_USER=weitzel
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    network_mode: "host"

    volumes:
      - ollama_data:/root/.ollama
    restart: unless-stopped

volumes:
  postgres_data:
  ollama_data: