services:
  database:
    image: docker.io/library/postgres:16-alpine
    container_name: trusty_chain_container
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=trusty_chain_db
      - POSTGRES_USER=trustychain_user
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

volumes:
  postgres_data: